# -*- coding: utf-8 -*-
"""predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JB92jFm1FMdX68DhUYYF7cbbOGkszEkt
"""

import sys
import json
import pandas as pd
import numpy as np
import joblib
import warnings
warnings.filterwarnings("ignore")
from feature_extraction import extract_features

def main():
    if len(sys.argv) < 2:
        print(json.dumps({"error": "Missing CSV path argument"}))
        return

    csv_path = sys.argv[1]

    # Load model & scaler
    model = joblib.load("best_model.pkl")
    scaler = joblib.load("scaler.pkl")

    # Read the voltage-current CSV (must have headers: Voltage,Current)
    df = pd.read_csv(csv_path)
    # Basic header robustness (accept Voltage/voltage; Current/current)
    cols_lower = {c.lower(): c for c in df.columns}
    if "voltage" not in cols_lower or "current" not in cols_lower:
        print(json.dumps({"error": "CSV must contain 'Voltage' and 'Current' columns"}))
        return

    V = df[cols_lower["voltage"]].to_numpy(dtype=float)
    I = df[cols_lower["current"]].to_numpy(dtype=float)

    # Extract features
    feats = extract_features(V, I)
    # Preserve order by iterating keys as created; optionally align to training feature order
    feature_list = [feats[k] for k in feats]

    # Scale and predict
    X = np.array(feature_list, dtype=float).reshape(1, -1)
    Xs = scaler.transform(X)
    pred = int(model.predict(Xs)[0])
    prob = float(model.predict_proba(Xs)[0][1])  # probability of class 1

    print(json.dumps({"prediction": pred, "probability": prob}))

if __name__ == "__main__":
    main()